# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Web Dev with Unicode
email: im@alistair.com
baseurl: "/unicode" # the subpath of your site, e.g. /blog
url: "http://alistair.com" # the base hostname & protocol for your site
twitter_username: alistaircalder
github_username:  alistaircom

# Build settings
markdown: kramdown
